apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-and-deploy-pipeline
spec:
  resources:
    - name: git-source
      type: git
  params:
    - name: pathToContextClient
      description: The path to the build context, used by Kaniko - within the workspace
      default: src
    - name: imageUrlClient
      description: Url of image repository
    - name: imageTag
      description: Tag to apply to the built image
    - name: pathToContextServer
      description: The path to the build context, used by Kaniko - within the workspace
      default: src
    - name: imageUrlServer
      description: Url of image repository
    - name: pathToContextWorker
      description: The path to the build context, used by Kaniko - within the workspace
      default: src
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
    - name: imageUrlWorker
      description: Url of image repository
  tasks:
  - name: source-to-image-client
    taskRef:
      name: source-to-image
    params:
      - name: pathToContext
        value: "$(params.pathToContextClient)"
      - name: imageUrl
        value: "$(params.imageUrlClient)"
      - name: imageTag
        value: "$(params.imageTag)"
    resources:
      inputs:
        - name: git-source
          resource: git-source
  - name: source-to-image-server
    taskRef:
      name: source-to-image
    params:
      - name: pathToContext
        value: "$(params.pathToContextServer)"
      - name: imageUrl
        value: "$(params.imageUrlServer)"
      - name: imageTag
        value: "$(params.imageTag)"
    resources:
      inputs:
        - name: git-source
          resource: git-source
  - name: source-to-image-worker
    taskRef:
      name: source-to-image
    params:
      - name: pathToContext
        value: "$(params.pathToContextWorker)"
      - name: imageUrl
        value: "$(params.imageUrlWorker)"
      - name: imageTag
        value: "$(params.imageTag)"
    resources:
      inputs:
        - name: git-source
          resource: git-source
  - name: deploy-to-cluster
    taskRef:
      name: deploy-using-kubectl
    runAfter:
      - source-to-image-client
      - source-to-image-server
      - source-to-image-worker
    params:
      - name: pathToYamlFile
        value:  "$(params.pathToYamlFile)"
    resources:
      inputs:
        - name: git-source
          resource: git-source